-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 20:19:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cafeinatopia_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cafeinatopia_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cafeinatopia_db` DEFAULT CHARACTER SET utf8 ;
USE `Cafeinatopia_db` ;

-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `createdAt` VARCHAR(255) NULL,
  `updatedAt` VARCHAR(255) NULL,
  `image` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `birthday` DATETIME NULL,
  `roleId` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `phone` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roleId`)
    REFERENCES `Cafeinatopia_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `province` VARCHAR(255) NOT NULL,
  `postalCode` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `usersId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_users_idx` (`usersId` ASC) VISIBLE,
  CONSTRAINT `fk_address_users`
    FOREIGN KEY (`usersId`)
    REFERENCES `Cafeinatopia_db`.`users` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`origins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`origins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`flavors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`flavors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `discount` INT NULL DEFAULT 0,
  `description` TEXT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `categoryId` INT NULL,
  `originId` INT NULL,
  `image` VARCHAR(255) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `flavorId` INT NULL,
  INDEX `fk_products_categories_idx` (`categoryId` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_products_origins_idx` (`originId` ASC) VISIBLE,
  INDEX `fk_products_flavors_idx` (`flavorId` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `Cafeinatopia_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_origins`
    FOREIGN KEY (`originId`)
    REFERENCES `Cafeinatopia_db`.`origins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_flavors`
    FOREIGN KEY (`flavorId`)
    REFERENCES `Cafeinatopia_db`.`flavors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`statuses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `total` INT NULL,
  `userId` INT NULL,
  `statusId` INT NULL,
  `orderDate` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_orders_statuses_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`userId`)
    REFERENCES `Cafeinatopia_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_statuses`
    FOREIGN KEY (`statusId`)
    REFERENCES `Cafeinatopia_db`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafeinatopia_db`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cafeinatopia_db`.`items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `orderId` INT NULL,
  `productsId` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_items_orders_idx` (`orderId` ASC) VISIBLE,
  INDEX `fk_items_products_idx` (`productsId` ASC) VISIBLE,
  CONSTRAINT `fk_items_orders`
    FOREIGN KEY (`orderId`)
    REFERENCES `Cafeinatopia_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_products`
    FOREIGN KEY (`productsId`)
    REFERENCES `Cafeinatopia_db`.`products` (`price`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
